SELECT * FROM customer LIMIT 20;

-- total revenue generated by male vs female
SELECT gender, SUM("purchase_amount") AS revenue
FROM customer
GROUP BY gender;

--which customer used a discound but still spend more than average purchase amount

select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--which are the top 5 products with highest average review rating

select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by AVG(review_rating::numeric) desc
limit 5;

--compare the average purchase amounts  between standard  and express  shippings

select shipping_type,round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


--do subcribed customer spend more compare average apend and total revenue 
--between subscribe and non-subscribes.
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

--which 5 products  have a the highest percentage of purchase with discount applied?

select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied= 'Yes' THEN 1 ELSE 0 END)/count(*)) as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5;

--segment customers into new, returnnning and loyal based on their  total 
--number of previous purchases, and show  the count of each segment

with customer_type as(
select customer_id,previous_purchases,
CASE
	when previous_purchases= 1 then 'NEW'
	when previous_purchases between 2 and 10  then 'Returning'
	else 'loyal'
	end as customer_segment
from customer
)
select customer_segment,count(*) as "Number of Custommers"
from customer_type
group by customer_segment;

--top 3 most purchased product with in each category

with item_counts as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

--are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyer
from customer
where previous_purchases >5
group by subscription_status;

--what is the revenue contribution of each ege group

SELECT age,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age
ORDER BY total_revenue DESC;



